package net.vellity.minecraft.common.spigot.item.textures

class Textures {
  companion object {
    const val ARROW_BACK_RED = "ewogICJ0aW1lc3RhbXAiIDogMTYwNjIyNDg3MjYyNCwKICAicHJvZmlsZUlkIiA6ICI3MmNiMDYyMWU1" +
      "MTA0MDdjOWRlMDA1OTRmNjAxNTIyZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJNb3M5OTAiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0c" +
      "nVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubm" +
      "V0L3RleHR1cmUvNGM5MDg2MmYzNTJjM2QzNmMxN2M4NDMxMTM2NDM5YjdjMGE5N2MxYmRlMjBjZmQ2MjM3YzIzOWIyNmZkMTk1IgogICA" +
      "gfQogIH0KfQ=="
    const val ARROW_UP_GOLD = "ewogICJ0aW1lc3RhbXAiIDogMTU5MjU5MDAxNDYzNiwKICAicHJvZmlsZUlkIiA6ICI0ZmFkNjk2NTIxN" +
      "GI0NGQ4YjAxYzlhZTVjZDQ0MDVjOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJoaXBfYXNpYW4iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOi" +
      "B0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQ" +
      "ubmV0L3RleHR1cmUvMzZmMmZlYzIzZWM3MTc4MjE2NDdjNTZhODM1YTM0YWZjYzY3NDVhNTFhODFjM2ZmYTBlOGExZGM5ZGVlM2U4Igog" +
      "ICAgfQogIH0KfQ=="
    const val ARROW_DOWN_GOLD = "ewogICJ0aW1lc3RhbXAiIDogMTU5MjU5MDUxMTcyNywKICAicHJvZmlsZUlkIiA6ICJkNjBmMzQ3MzZ" +
      "hMTI0N2EyOWI4MmNjNzE1YjAwNDhkYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCSl9EYW5pZWwiLAogICJzaWduYXR1cmVSZXF1aXJlZCIg" +
      "OiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZ" +
      "nQubmV0L3RleHR1cmUvYmE5YjJlZjQ4NTI1YjQzMzM4Y2QxMjZjZTgyNDBkNTVhZDE5OTk4M2JjNjc4YWRkNTIzZWU0YWU4NGE0M2IwNC" +
      "IKICAgIH0KICB9Cn0="
    const val PLUS_RED = "ewogICJ0aW1lc3RhbXAiIDogMTU5MTAxMzc0NTcwNiwKICAicHJvZmlsZUlkIiA6ICJhNzFjNTQ5MmQwNTE0ZD" +
      "g3OGFiOTEwZmRmZmRmYzgyZiIsCiAgInByb2ZpbGVOYW1lIiA6ICJBcHBsZTU0NDciLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnV" +
      "lLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0" +
      "L3RleHR1cmUvNWU1ZjVjMTkxN2MxZTczZDExOWI0NTFjZmJlMjczZWQ4MjFlZGU4NjdiYjM2YWU3MjcxOTQ5MTc5NjRiZWVjOSIKICAgI" +
      "H0KICB9Cn0="
    const val PLUS_GREEN = "ewogICJ0aW1lc3RhbXAiIDogMTY3MTEzMDM0NDUwOSwKICAicHJvZmlsZUlkIiA6ICI5MWYwNGZlOTBmMzY0" +
      "M2I1OGYyMGUzMzc1Zjg2ZDM5ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJTdG9ybVN0b3JteSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6I" +
      "HRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC" +
      "5uZXQvdGV4dHVyZS9jNmU1NjIyMDk5ZThmZjcwMDgxZjQ0NDAxMzE3NGFlMmM4MzQwMDgxNzBiMjQxZmRjYTMxODAyYjYwNzQ1ZmFhIgo" +
      "gICAgfQogIH0KfQ=="
    const val PLUS_OAK = "ewogICJ0aW1lc3RhbXAiIDogMTYyMTE2Nzk2MjA0OCwKICAicHJvZmlsZUlkIiA6ICIzM2ViZDMyYmIzMzk0YW" +
      "Q5YWM2NzBjOTZjNTQ5YmE3ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJEYW5ub0JhbmFubm9YRCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA" +
      "6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFm" +
      "dC5uZXQvdGV4dHVyZS9mNjFkZWViZWNhMGRlMzA3NGU0YTZmN2Y1NWIyYjUxNTA0NGE2YmU0N2QxZDllYmJkNTNlMWIzNTkxZTEwYWQxI" +
      "iwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0="
    const val PAUSE_RED = "ewogICJ0aW1lc3RhbXAiIDogMTY1MzAyMjk5NzIwNSwKICAicHJvZmlsZUlkIiA6ICI5ZWU3NTUxOGQyZWE0Y" +
      "2Q4OGJiNGI1YTZkNmVhNTFjYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJNaWNyb3MxMTgyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdH" +
      "J1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5" +
      "ldC90ZXh0dXJlL2RjNDY3YzU3N2VjMjVkZmE1YjlmODU0N2MzM2ExYmM3YWRmY2QyODE2NGFjNTQ4MDllYzliNzUxMmNjMzViMWIiLAog" +
      "ICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
    const val MINUS_RED = "ewogICJ0aW1lc3RhbXAiIDogMTU5Mzg3MjY1MTU2MywKICAicHJvZmlsZUlkIiA6ICJlNzkzYjJjYTdhMmY0M" +
      "TI2YTA5ODA5MmQ3Yzk5NDE3YiIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGVfSG9zdGVyX01hbiIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIi" +
      "A6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmF" +
      "mdC5uZXQvdGV4dHVyZS8yNDMwZjY3YzBmZDk0ZTg1ZGMyMjNiOTE4N2IwODE1NWZkNjYyZDdhZjYyZGIyYmMzNDEzMWU2MTQyZTkxZTA0" +
      "IgogICAgfQogIH0KfQ=="
    const val QUESTION_MARK_OAK = "ewogICJ0aW1lc3RhbXAiIDogMTU4OTM4MzA1MzYwNSwKICAicHJvZmlsZUlkIiA6ICIzZmM3ZmRmOTM5N" +
      "jM0YzQxOTExOTliYTNmN2NjM2ZlZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJZZWxlaGEiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cn" +
      "VlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV" +
      "0L3RleHR1cmUvY2I0MzJjNmJlZTAxOTlhZDZmMDg2MDJjZGYyN2RmOWI2NjY5ZTE1MDYzMDVmM2Y0NTkwNWI1YjA0NDQ1ZjA0NyIsCiAg" +
      "ICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
  }
}